name: State of the Ecosystem - Catalog Submission
description: Use this issue template to submit catalog information for the State of the Ecosystem reports.
title: "[Submission]: "
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the State of the Ecosystem reports! Please reach out to nefsc.soe.leads@noaa.gov with any questions or concerns.
  - type: input
    id: contact1
    attributes:
      label: Primary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: true
  - type: input
    id: contact2
    attributes:
      label: Secondary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: false
  - type: input
    id: data_name
    attributes:
      label: Data Name
      description: Enter the name of the data set.
      placeholder: Ex. NE Shelf Annual Sea Surface Temperature
    validations:
      required: true
  - type: textarea
    id: data_description
    attributes:
      label: Data Description
      description: Briefly describe the data set.
      value: "Ex: The data presented here are average annual sea-surface temperatures from PSL OISST on the Northeast Continental Shelf."
    validations:
      required: true
  - type: checkboxes
    id: synthesis_theme
    attributes:
      label: Synthesis Theme
      description: Please check the synthesis theme(s) that could apply to your indicator.
      options:
        - label: Multiple System Drivers
        - label: Regime Shifts
        - label: Ecosystem Reorganization
          required: false
  - type: input
    id: data-url
    attributes:
      label: Can you provide a URL to view the data online?
      description: Please provide a link to the data, whether http, ftp, or other.
      placeholder: ex. https://www.fisheries.noaa.gov/inport/stats/NEFSC/data-sets
    validations:
      required: false
  - type: dropdown
    id: data-type
    attributes:
      label: What is the type of data?
      description: Spatial data type for the requested addition.
      multiple: false
      options:
        - Shapefile
        - Raster
        - Other (please specify below)
    validations:
      required: true      
  - type: input
    id: data-type-other
    attributes:
      label: If Other, please specify data type
      description: If you selected Other from the dropdown menu above, please specify the spatial data type.
      placeholder: ex. Geodatabase (*.gdb)
    validations:
      required: false
  - type: dropdown
    id: data-manip
    attributes:
      label: Does this data require any additional manipulation before usage?
      description: If yes, and upon acceptance, a pull request will need to be initiated containing the R code. You will be instructed when to do this.
      multiple: false
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true 
  - type: checkboxes
    id: assign-reviewer
    attributes:
      label: Have you assigned 2 reviewers for this new data submission request?
      description: Please assign 2 team members (@andybeet, @jmhatch, @kimberly-bastille) to review this new data submission request.
      options:
        - label: I have assigned 2 reviewers
          required: true
